# Generated by Django 4.1.3 on 2022-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_item_active_item_is_active_item_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
