# Generated by Django 4.1.3 on 2022-12-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_memberprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile'),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
