# Generated by Django 4.1.3 on 2023-01-01 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_comment_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
